# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o28vVXYGd5eDbrBrlWNCnPBU7oBTIEpF
"""

import streamlit as st
import numpy as np

st.title("Simple ML Model Deployment 🚀")
st.write("This model predicts y = 2x")

input_value = st.number_input("Enter a number", value=1.0)

if st.button("Predict"):
    prediction = 2 * input_value
    st.success(f"Predicted Output: {prediction:.2f}")