# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o28vVXYGd5eDbrBrlWNCnPBU7oBTIEpF
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import tensorflow as tf
# import numpy as np
# 
# st.title("🚀 TensorFlow Model Deployment Demo")
# 
# @st.cache_resource
# def load_model():
#     return tf.keras.models.load_model("model.keras")
# 
# model = load_model()
# 
# user_input = st.number_input("Enter a number", value=1.0)
# 
# if st.button("Predict"):
#     prediction = model.predict(np.array([[user_input]]))
#     st.success(f"Prediction: {prediction[0][0]:.2f}")
